### ISSUE TITLE
Unmatched Foreign Key Reference

### ISSUE THREAD

**Issue by LPerryman** [ONS-OpenData/ONS-LTIM-Area-of-Destination-or-Origin#1]
$ docker top 66348bf81cf02ecf3ef1e7cbb7ced5bf593b484dfdd00e8773d966765f809b48 -eo pid,comm
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] ansiColor
[Pipeline] {
[Pipeline] sh
+ csvlint -s schema.json
invalid metadata: malformed JSON
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // script
[Pipeline] }

**Comment by RedWalters** [comment]
Reference data missing relevant entry required for data marker:
unmatched_foreign_key_reference. Row: 3,10. ["statistically-significant-decrease"]

**Comment by LPerryman** [comment]
Meta dat at bottom of table sheet was being pulled in (Statistically Significant Decrease) and added to the table. Fixed this problem but the pipeline now fails when 'Uploading Tidy Data', not much to go on in the console output. will close this but open another issue.
